### ISSUE TITLE
Example script?

### ISSUE THREAD

**Issue by willwright82** [jwaterfaucett/bugherd_client#1]
Hi there! Very pleased to find this client for Bugherd, but I haven't been able to write a script using it… 😞

Could you show me an example script that would display a project's current "todo" list tasks?

Cheers!

**Comment by Phillipdawson7** [comment]
@willwright82 I am looking to introduce this to my process did you get it to work and would you be able to point me in any direction of using it. I know its an old post but am just hoping its still something you use.

**Comment by willwright82** [comment]
@Phillipdawson7 Sorry, have since moved away from this… No luck
